export const RESERVATION_LABEL_KEY = [
  { "label": "RSVP No", "value": "rsvp_no" },
  { "label": "Room Type", "value": "room_type" },
  { "label": "Room No", "value": "room_no" },
  { "label": "Room Count", "value": "room_count" },
  { "label": "Last Name", "value": "last_name" },
  { "label": "First Name", "value": "first_name" },
  { "label": "Adult Pax", "value": "pax_adult" },
  { "label": "Child Pax", "value": "pax_child" },
  { "label": "Arrival Date", "value": "arrival_date" },
  { "label": "Departure Date", "value": "departure_date" },
  { "label": "ETA By", "value": "eta_by" },
  { "label": "Voucher No", "value": "voucher_no" },
  { "label": "Group Name", "value": "group_name" },
  { "label": "Rate Source", "value": "rate_source" },
  { "label": "Deposit Amount", "value": "deposit_amount" },
  { "label": "Status", "value": "sts" },
  { "label": "User", "value": "us" },
  { "label": "RSVP Type", "value": "rsvp_type" },
  { "label": "Non Refundable", "value": "non_refundable" },
  { "label": "RNW", "value": "rnw" }
];

const FIRST_NAME = "AFIQ FAISAL";

export const AUTO_RESERVATION = {
  rsvpDate: "2025-12-01",
  rsvpNo: "RS1P100679",
  arrival: "2025-12-19",
  departure: "2025-12-21",
  nights: 2,
  rateSource: "TRIP.COM",
  rateGroup: "Published",
  reservationMode: "Individual",
  type: "Confirmed",
  firstName: FIRST_NAME,
  lastName: "ABDUL KADIR",

  accommodation: [],
  inventorySource: "Allotment",
  reservationType: "FIT",
  confirmation: "Email",
  confirmationBy: "Front Desk",
  sellingType: "Room Only",
  noteDetail: "Late arrival, please hold the room.",
  rate: [],

  purposeOfVisit: "Leisure",
  sourceOfBusiness: "OTA",
  segmentMarket: "Online",
  reservedBy: "TRIP.COM",
  booker: "TRIP.COM",
  bookingSource: "TRIP.COM",
  companyRsvp: "",
  phoneNumberRsvp: "+62-812-0000-0000",
  promo: "YEAR-END-25",
  email: "afiq@example.com",
  ETA: "2025-12-19T15:00:00+07:00",
  ETD: "2025-12-21T12:00:00+07:00",
  ETDby: "Front Desk",
  ETAby: "Guest",
  courtesyArrival: "Yes",
  courtesyDeparture: "No",
  billingInstruction: "Charge room & tax to guest.",
  paymentInstruction: "Preauth on check-in; settle at check-out.",
  guestNote: "Allergic to peanuts.",

  titleName: "Mr.",
  salutation: "Dear",
  homeAddress: "Jl. Mawar No. 10, Jakarta",
  country: "Indonesia",
  city: "Jakarta",
  nationality: "Indonesia",
  language: "ID",
  phoneNumberDetail: "+62-812-0000-0000",
  altPhoneNumberDetail: "",
  emailDetail: "afiq@example.com",
  mobileDetail: "afiq.mobile@example.com",
  faxDetail: "",
  guestIdType: "Passport",
  guestId: "A123456789",
  guestType: "VIP",
  specialDate: "2025-12-20",
  specialDateNote: "Anniversary",
  companyDetail: "",
  position: "",
  companyAddress: "",
  companyPhoneDetail: "",
  companyFax: "",
  companySite: "",

  paidMethod: "Credit Card",
  cardType: "VISA",
  cardId: "**** **** **** 1234",
  validMonth: "12",
  validYear: "27",
  preAmount: "0",
  approvalCode: "",
  arAccountInformation: "",

  deposit: {
    id: "",
    date: "2025-12-10",
    description: "Prepayment",
    amount: 0,
  },

  member: {
    id: "",
    memberId: "MEM-0001",
    name: FIRST_NAME,
    validUntil: "2026-12-31",
    sts: "Active",
  },

  leisureBooking: [
    {
      takenDate: "2025-12-01 09:30",
      leisureGroup: "Spa",
      lastName: "ABDUL KADIR",
      firstName: FIRST_NAME,
      bookingForDatetime: "2025-12-20 17:00",
      time: "2025-12-20",
      qty: 2,
      ref: "SPA-REF-001",
      notes: "Couple massage",
      followUpDatetime: "2025-12-19 10:00",
      followUpBy: "Concierge",
      followUpId: "EMP-100",
      followUpNotes: "Confirmed via phone",
    },
  ],

  reminder: [
    {
      takenDatetime: "2025-12-01 10:00",
      subject: "Anniversary amenity",
      remindOnDatetime: "2025-12-20 12:00",
      message: "Place cake & flowers in room at 6 PM.",
      followUpDatetime: "2025-12-20 13:00",
      followUpBy: "Guest Relations",
      followUpId: "EMP-102",
      followUpNotes: "Amenity arranged",
    },
  ],

  inventoryReq: [
    {
      takenDatetime: "2025-12-18 16:00",
      inventoryGroup: "Housekeeping",
      inventoryItem: "Baby crib",
      onHand: "5",
      borrowed: "0",
      borrowedBalance: "5",
      ref: "HK-REQ-001",
      notes: "Deliver before 8 PM",
      followUpDatetime: "2025-12-19 18:30",
      followUpBy: "HK",
      followUpId: "EMP-210",
      followUpNotes: "Delivered",
    },
  ],

  idLeaderGroup: null,
  leaderNameGroup: null,
  groupNotes: null,
  roomNotesGroup: null,
  fnbNotesGroup: null,
  roomingListGroup: null,
  notesDetail: null,
};

