import { lazy } from 'react';
export default {
  Login: lazy(() => import('./Login')),
  Register: lazy(() => import('./Register')),
  GuestAccount: lazy(() => import('./Cashier/GuestAccount')),
  BatchPosting: lazy(() => import('./Cashier/BatchPosting')),
  Detail: lazy(() => import('./Detail')),
  Dashboard: lazy(() => import('./Dashboard')),
  GuestList: lazy(() => import('./Guest/GuestList')),
  Profile: lazy(() => import('./Profile')),
  Settings: lazy(() => import('./Setting')),
  ListReservation: lazy(() => import('./Reservation/ListReservation')),
  GuestInHouse: lazy(() => import('./Reservation/GuestInHouse')),
  Deposit: lazy(() => import('./Cashier/Deposit')),
  RegisterReservationForm: lazy(() => import('./Reservation/RegisterForm')),
  NewReservationForm: lazy(() => import('./Reservation/ListReservation/NewReservationForm')),
  Reception: lazy(() => import('./Reception')),
  ReportInvoice: lazy(() => import('./Report/Invoice')),
  Unauthorized: lazy(() => import('./Unauthorized')),
  NotFound: lazy(() => import('./NotFound')),
};
