import { lazy } from 'react';
export default {
  Login: lazy(() => import('./Login')),
  Register: lazy(() => import('./Register')),
  Cashier: lazy(() => import('./Cashier')),
  Detail: lazy(() => import('./Detail')),
  Dashboard: lazy(() => import('./Dashboard')),
  Deposit: lazy(() => import('./Deposit')),
  GuestList: lazy(() => import('./Guest/GuestList')),
  Profile: lazy(() => import('./Profile')),
  LostFound: lazy(() => import('./LostFound')),
  Settings: lazy(() => import('./Setting')),
  ListReservation: lazy(() => import('./Reservation/ListReservation')),
  Registration: lazy(() => import('./Registration')),
  NightAudit: lazy(() => import('./NightAudit')),
  GuestInHouse: lazy(() => import('./Reservation/GuestInHouse')),
  RegisterReservationForm: lazy(() => import('./Reservation/RegisterForm')),
  NewReservationForm: lazy(() => import('./Reservation/ListReservation/NewReservationForm')),
  Reception: lazy(() => import('./Reception')),
  Room: lazy(() => import('./Room')),
  Report: lazy(() => import('./Report')),
  Unauthorized: lazy(() => import('./Unauthorized')),
  NotFound: lazy(() => import('./NotFound')),
};
